version: "3.8"

services:
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    ports:
      - "8080:8080"
      - "8088:8088"
      - "9000:9000"
      - "9870:9870"
      - "19888:19888"
      - "7077:7077"
    volumes:
      - /c/Users/otari/OneDrive/Documents/hadoop_project:/home/hadoop/lab0
    command: tail -f /dev/null

  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    ports:
      - "8040:8042"
    command: tail -f /dev/null

  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    ports:
      - "8041:8042"
    command: tail -f /dev/null
